### ISSUE TITLE
모바일 그림 일기 추가로 인한 버그

### ISSUE THREAD

**Issue by c9u11** [LeeSeungjae00/modoo-diary#23]
<img width="545" alt="image" src="https://github.com/LeeSeungjae00/modoo-diary/assets/29428714/01ddd52b-86e9-446d-8e0d-cef8c7702dcc">

pc에서 그림일기 클릭 시 스크롤이 되지않아 해제할 수 없음

**Comment by LeeSeungjae00** [comment]
해결 완료 했읍니다.
